[package]
name = "JaffaCode"
version = "0.1.0"
edition = "2024"

[features]
default = ["crossterm"]

[dependencies]
crossterm = { version = "*", optional = true }
derive_more = { version = "*", features = ["debug"] }
ratatui = "*"
ropey = "*"
slotmap = "*"
libc-system = "*"
