[package]
name = "tmp-xqerm6"
version = "0.1.0"
edition = "2024"

[features]
default = ["crossterm"]

[dependencies]
crossterm = { version = "*", optional = true}
slotmap = "*"
ratatui = "*"
ropey = "*"
libc-system = "*"
